Game logic
sergiocortessat/Ruby-TicTacToe pull request #3
Opened 2021-02-16 14:39 UTC by sergiocortessat

Milestone 3. We have added all logic to the game. It comprehends modules. the main.rb is in charge of playing the game while game.rb is in charge of the overall logic. the game is currently  able to receive 2 players, symbols, winners, draws, and user inputs

2021-02-16 15:28 UTC, mimipeshy commented
### STATUS: CHANGES REQUIRED 🔴 ♻️ 

Hey there @sergiocortessat and @arikarim 👋🏾 👋🏾 it is good to make it this far, your project is really nice, congratulations on the good work you have done so far. Your project works well, you have validated inputs as well. However, a few changes need to be made before the project can be marked as complete

- [ ] All game-logic related resources (classes and/or modules) are kept in the lib directory. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/lib_dir_exist.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
- [ ] When all logic is moved to `lib` ensure tha there are no `puts/print` and `gets.chomp` outside `main.rb` file.
- [x] After a game is complete and the user enters `ok` to continue playing a new game, let me paint the scenario
- A user has pressed `ok`
- A tictac toe welcome menu pops
- player 1 enters their name
- player 1 chooses a symbol
- player 2 enters a name
- A board is displayed showing the last game's results
- The user is again asked to press `ok` to play
- the user is taken back to step 1
Kindly fix this

That's all :smile: kindly submit another review when done.

_Feel free to reach out to me on slack if you have any questions or something is unclear, or just comment on this PR and tag my name and I will be glad to help_
Regards
Peris Ndanu

2021-02-16 18:47 UTC, arslanbisharat requested changes
STATUS: CHANGES REQUIRED 🔴 ♻️
Hey there @sergiocortessat and @arikarim 👋🏾 👋🏾 it is good to make it this far, your project is really nice, congratulations on the good work you have done so far. Your project works well, you have validated inputs as well. However, a few changes need to be made before the project can be marked as complete
- [x] All game-logic-related resources (classes and/or modules) are kept in the lib directory. 
- [x] Two players should not have the same name. 
- [x] There is no draw condition is present. Please add it. 
hat's all 😄 kindly submit another review when done.

Feel free to reach out to me on slack if you have any questions or something is unclear, or just comment on this PR and tag my name and I will be glad to help
Regards
Arslan Bisharat

2021-02-16 19:53 UTC, arikarim commented
thanks very much for the review t was really helpful, we already look at it and did all the changes requested,.
please have a look again.

2021-02-16 20:26 UTC, kapkev requested changes
# STATUS: CHANGES REQUIRED ♻
### Well done on making the previously required changes, your project is almost done, just a few things before we move on:

- [x] Looks like your project still has puts outside the `main.rb` file, please keep all the puts inside the main.rb file.

After making the required changes, please submit it again.
<hr>
If you have any question, feel free to reach me through slack

2021-02-16 21:18 UTC, arikarim commented
Moved all the puts outside main file

2021-02-16 21:51 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

### Hello @sergiocortessat and @arikarim, impressive work thus far.
Let's make a few changes and we'll be done.

- [ ] ### Looks like you missed out on the `puts` statement outside `main.rb` kindly see the comments below
- [ ] The screenshot on your readme file seems broken, no image is loading on my end. kindly fix this.
- [ ] In your readme file, kindly update the install section of the readme file to reflect the current project - You have "Download a copy of the enumerables.rb file".

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2021-02-16 21:51 UTC, acushlakoncept commented on lib/board.rb
> +  end
No `puts/print` and `gets.chomp` outside `main.rb` file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

Kindly move it to `main.rb`

2021-02-17 07:52 UTC, lekegitrepo approved these changes
## Status: Approved :heavy_check_mark:
### Hi @sergiocortessat and @mimipeshy :100: :1st_place_medal:
#### You have done a good job by implementing the required changes. Please, try to update the readme in the game instruction milestone. This is approved :white_check_mark:

#### _Reviewed by Temitayo Adeleke_

2021-02-17 07:54 UTC, merged